version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  web:
    build: .
    environment:
      [DJANGO_SECRET_KEY,
      POSTGRES_PASSWORD]
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
