# Generated by Django 3.0.5 on 2020-04-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sluggen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slug',
            name='id',
        ),
        migrations.AlterField(
            model_name='slug',
            name='slug',
            field=models.SlugField(max_length=7, primary_key=True, serialize=False, verbose_name='shortened version of the URL'),
        ),
    ]
